import { AtomType, encodeDatagram, encodeSurface, encodeRawSurface, FCST_HEADER_BYTES, REGION_COLUMNS, REGION_ROWS } from "@flexcast/protocol-types";

type FrameMessage = { type: "frame"; bitmap: ImageBitmap; frameTick: number; maxDatagram: number; budgetBytes: number; highQuality?: boolean };
type InitMessage = { type: "init"; epoch: number };
let epoch = 1; let sequence = 0; const previous = new Uint8Array(REGION_COLUMNS * REGION_ROWS * 48); const previousChromaA = new Int8Array(REGION_COLUMNS * REGION_ROWS * 12); const previousChromaB = new Int8Array(REGION_COLUMNS * REGION_ROWS * 12); const stateIds = new Uint32Array(REGION_COLUMNS * REGION_ROWS);
const analysisCanvas = new OffscreenCanvas(480, 270); const analysisContext = analysisCanvas.getContext("2d", { willReadFrequently: true }); const surfaceCanvas = new OffscreenCanvas(1920, 1080); const surfaceContext = surfaceCanvas.getContext("2d", { willReadFrequently: true });

self.onmessage = (event: MessageEvent<FrameMessage | InitMessage>) => { if (event.data.type === "init") { epoch = event.data.epoch; sequence = 0; previous.fill(0); previousChromaA.fill(0); previousChromaB.fill(0); stateIds.fill(0); return; } void process(event.data); };
async function process(message: FrameMessage): Promise<void> {
  if (!analysisContext || !surfaceContext) return; analysisContext.drawImage(message.bitmap, 0, 0, 480, 270); surfaceContext.drawImage(message.bitmap, 0, 0, 1920, 1080); message.bitmap.close();
  const pixels = analysisContext.getImageData(0, 0, 480, 270).data; const candidates: { score: number; region: number; luma: Uint8Array; chromaA: Int8Array; chromaB: Int8Array; }[] = [];
  for (let region = 0; region < REGION_COLUMNS * REGION_ROWS; region++) { const luma = new Uint8Array(48); const ca = new Int8Array(12); const cb = new Int8Array(12); const row = Math.floor(region / REGION_COLUMNS); const col = region % REGION_COLUMNS;
    for (let gy = 0; gy < 6; gy++) for (let gx = 0; gx < 8; gx++) { const pixel = (((row * 6 + gy) * 480) + col * 8 + gx) * 4; const r = pixels[pixel] ?? 0, g = pixels[pixel + 1] ?? 0, b = pixels[pixel + 2] ?? 0; luma[gy * 8 + gx] = (r + 2 * g + b) >> 2; }
    for (let gy = 0; gy < 3; gy++) for (let gx = 0; gx < 4; gx++) { let a = 0, b = 0; for (let sy = 0; sy < 2; sy++) for (let sx = 0; sx < 2; sx++) { const pixel = (((row * 6 + gy * 2 + sy) * 480) + col * 8 + gx * 2 + sx) * 4; const r = pixels[pixel] ?? 0, g = pixels[pixel + 1] ?? 0, blue = pixels[pixel + 2] ?? 0; a += r - g; b += blue - g; } ca[gy * 4 + gx] = Math.max(-128, Math.min(127, Math.round(a / 4))); cb[gy * 4 + gx] = Math.max(-128, Math.min(127, Math.round(b / 4))); }
    let delta = 0; const offset = region * 48; const chromaOffset = region * 12; for (let i = 0; i < 48; i++) delta += Math.abs((luma[i] ?? 0) - (previous[offset + i] ?? 0)); for (let i = 0; i < 12; i++) delta += Math.abs((ca[i] ?? 0) - (previousChromaA[chromaOffset + i] ?? 0)) + Math.abs((cb[i] ?? 0) - (previousChromaB[chromaOffset + i] ?? 0));
    const ageScore = message.frameTick % 15 === region % 15 ? 20 : 0; if (delta < 80 && ageScore === 0) continue;
    const payloadBytes = message.highQuality ? 1 + 32 * 24 * 3 : 73; if (FCST_HEADER_BYTES + payloadBytes <= message.maxDatagram) candidates.push({ score: delta + ageScore, region, luma, chromaA: ca, chromaB: cb });
  }
  candidates.sort((a, b) => b.score - a.score); let used = 0; const selected: ArrayBuffer[] = []; for (const candidate of candidates) { const payloadBytes = message.highQuality ? 1 + 32 * 24 * 3 : 73; const atomBytes = FCST_HEADER_BYTES + payloadBytes; if (used + atomBytes > message.budgetBytes) continue; let payload: Uint8Array; if (message.highQuality) { const raw = new Uint8Array(32 * 24 * 3); const row = Math.floor(candidate.region / REGION_COLUMNS); const col = candidate.region % REGION_COLUMNS; const source = surfaceContext.getImageData(col * 32, row * 24, 32, 24).data; for (let pixel = 0; pixel < 32 * 24; pixel++) { const input = pixel * 4; const output = pixel * 3; raw[output] = source[input] ?? 0; raw[output + 1] = source[input + 1] ?? 0; raw[output + 2] = source[input + 2] ?? 0; } payload = encodeRawSurface(raw); } else { payload = encodeSurface(candidate.luma, candidate.chromaA, candidate.chromaB); } const nextState = (stateIds[candidate.region] ?? 0) + 1; const header = { atomType: AtomType.Surface, flags: 1, sessionEpoch: epoch, atomSequence: ++sequence, frameTick: message.frameTick, regionId: candidate.region, fragmentIndex: 0, fragmentCount: 1, stateId: nextState, baseStateId: 0, captureTimeMs: Math.floor(performance.now()), ttlMs: 120 }; const packet = encodeDatagram(header, payload); used += packet.byteLength; previous.set(candidate.luma, candidate.region * 48); previousChromaA.set(candidate.chromaA, candidate.region * 12); previousChromaB.set(candidate.chromaB, candidate.region * 12); stateIds[candidate.region] = nextState; selected.push(packet.buffer as ArrayBuffer); }
  (self as unknown as { postMessage: (message: unknown, transfer: Transferable[]) => void }).postMessage({ type: "atoms", packets: selected, generated: candidates.length, sentBytes: used }, selected);
}
