import "./style.css";

const byId = <T extends HTMLElement>(id: string): T => document.getElementById(id) as T;
const video = byId<HTMLVideoElement>("preview"), notice = byId<HTMLDivElement>("notice"), edgeInput = byId<HTMLInputElement>("edge-url"), preflightButton = byId<HTMLButtonElement>("preflight"), startButton = byId<HTMLButtonElement>("start"), stopButton = byId<HTMLButtonElement>("stop"), diagnostics = byId<HTMLPreElement>("diagnostics");
const resolution = byId<HTMLElement>("resolution"), connection = byId<HTMLElement>("connection"), fps = byId<HTMLElement>("fps"), bitrate = byId<HTMLElement>("bitrate");
let stream: MediaStream | undefined; let transport: WebTransport | undefined; let writer: WritableStreamDefaultWriter<Uint8Array> | undefined; let worker: Worker | undefined; let frameTick = 0; let lastFrameAt = 0; let sentBytes = 0; let startedAt = 0;
const targetBitrate = 12_000_000;
const joinParameters = new URLSearchParams(window.location.search);
const invitedEdge = joinParameters.get("edge");
if (invitedEdge) edgeInput.value = invitedEdge;
function show(text: string, kind = ""): void { notice.textContent = text; notice.className = `notice ${kind}`; }
function report(lines: Record<string, string | number | boolean>): void { diagnostics.textContent = Object.entries(lines).map(([key, value]) => `${key}: ${value}`).join("\n"); }
async function preflight(): Promise<void> { preflightButton.disabled = true; show("FlexCast接続テスト中…"); try { if (!window.isSecureContext) throw new Error("FC1101 HTTPS secure context is required"); if (!navigator.mediaDevices?.getUserMedia) throw new Error("FC1001 camera capture is unavailable"); if (!("WebTransport" in window)) throw new Error("FC1101 WebTransport is unavailable"); if (!("Worker" in window)) throw new Error("FC1201 Worker is unavailable"); if (!("gpu" in navigator)) throw new Error("FC1201 WebGPU is unavailable; strict FHD30 cannot start");
    stream = await navigator.mediaDevices.getUserMedia({ video: { width: { ideal: 1920, min: 1920 }, height: { ideal: 1080, min: 1080 }, frameRate: { ideal: 30, min: 30 }, facingMode: { ideal: "environment" } }, audio: true }); video.srcObject = stream; await video.play(); const settings = stream.getVideoTracks()[0]?.getSettings(); if (!settings || (settings.width ?? 0) < 1920 || (settings.height ?? 0) < 1080) throw new Error("FC1002 FHD camera is unavailable"); if ((settings.frameRate ?? 0) < 29.5) throw new Error("FC1003 30fps camera is unavailable"); const gpu = (navigator as Navigator & { gpu?: { requestAdapter: () => Promise<unknown> } }).gpu; const adapter = await gpu?.requestAdapter(); if (!adapter) throw new Error("FC1201 WebGPU adapter is unavailable");
    resolution.textContent = `${settings.width}×${settings.height}`; fps.textContent = `${settings.frameRate?.toFixed(1)} fps`; connection.textContent = "Ready"; show("FHD30の条件を確認しました。配信を開始できます。", "ok"); report({ secureContext: window.isSecureContext, width: settings.width ?? 0, height: settings.height ?? 0, fps: settings.frameRate ?? 0, webTransport: true, webGPU: true, audio: stream.getAudioTracks().length > 0 }); startButton.disabled = false;
  } catch (error) { const message = error instanceof Error ? error.message : "unknown preflight error"; show(`この端末または通信環境では FlexCast FHD30の動作条件を満たしていません。 ${message}`, "error"); report({ error: message }); stop(); } finally { preflightButton.disabled = false; } }
async function start(): Promise<void> { if (!stream) return; const url = edgeInput.value.trim(); if (!url.startsWith("https://")) { show("FC1103 HTTPSのFlexCast Edge URLを入力してください。", "error"); return; } try { show("FlexCast Edgeへ接続中…"); transport = new WebTransport(url); await transport.ready; if (transport.datagrams.maxDatagramSize < 114) throw new Error("FC1102 Edge datagram size is too small"); writer = transport.datagrams.writable.getWriter(); const control = await transport.createBidirectionalStream(); const hello = new TextEncoder().encode(JSON.stringify({ type: "HELLO", protocol: "FCST/1", client: "sender-web", invite: joinParameters.get("invite"), video: { width: 1920, height: 1080, fps: 30 } })); const controlPacket = new Uint8Array(4 + hello.byteLength); new DataView(controlPacket.buffer).setUint32(0, hello.byteLength); controlPacket.set(hello, 4); const controlWriter = control.writable.getWriter(); await controlWriter.write(controlPacket); controlWriter.releaseLock(); worker = new Worker(new URL("./analysis-worker.ts", import.meta.url), { type: "module" }); worker.postMessage({ type: "init", epoch: crypto.getRandomValues(new Uint32Array(1))[0] ?? 1 }); worker.onmessage = (event: MessageEvent<{ type: string; packets: ArrayBuffer[]; generated: number; sentBytes: number }>) => { if (event.data.type !== "atoms" || !writer) return; for (const packet of event.data.packets) void writer.write(new Uint8Array(packet)); sentBytes += event.data.sentBytes; };
    startedAt = performance.now(); frameTick = 0; connection.textContent = "Connected"; bitrate.textContent = "12.0 Mbps"; startButton.disabled = true; stopButton.disabled = false; show("配信中 — 1080p30を維持し、Visual Atomを同期しています。", "ok"); scheduleFrame(); document.addEventListener("visibilitychange", visibility); void navigator.wakeLock?.request("screen").catch(() => undefined);
  } catch (error) { show(`FC1103 Edge接続に失敗しました。 ${error instanceof Error ? error.message : ""}`, "error"); stop(); } }
function scheduleFrame(): void { if (!worker || !transport) return; video.requestVideoFrameCallback(async (_now, metadata) => { if (!worker || !transport) return; const bitmap = await createImageBitmap(video); frameTick++; const elapsed = Math.max(1, performance.now() - startedAt); const budgetBytes = Math.max(114, Math.floor((targetBitrate / 8) / 30)); worker.postMessage({ type: "frame", bitmap, frameTick, maxDatagram: transport.datagrams.maxDatagramSize, budgetBytes }, [bitmap]); if (lastFrameAt) fps.textContent = `${(1000 / (metadata.expectedDisplayTime - lastFrameAt)).toFixed(1)} fps`; lastFrameAt = metadata.expectedDisplayTime; bitrate.textContent = `${((sentBytes * 8 / elapsed) / 1_000_000).toFixed(1)} Mbps`; scheduleFrame(); }); }
function visibility(): void { if (document.visibilityState === "hidden") show("FC1601 バックグラウンドではFlexCastを継続できません。画面を開いたままにしてください。", "error"); }
function stop(): void { worker?.terminate(); worker = undefined; writer?.releaseLock(); writer = undefined; transport?.close({ reason: "sender stopped" }); transport = undefined; stream?.getTracks().forEach((track) => track.stop()); stream = undefined; video.srcObject = null; startButton.disabled = true; stopButton.disabled = true; connection.textContent = "Stopped"; document.removeEventListener("visibilitychange", visibility); }
preflightButton.addEventListener("click", () => void preflight()); startButton.addEventListener("click", () => void start()); stopButton.addEventListener("click", stop);
if (invitedEdge) {
  show("招待リンクを開きました。カメラの許可を求めます。");
  void preflight();
}
